// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joaqibukfiipdvtnnqtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvYXFpYnVrZmlpcGR2dG5ucXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDkxMjIsImV4cCI6MjA2NzYyNTEyMn0.jviEOeJVqC1ajBYaJusN5HNi9PKE0FlYrH3Wj8CJAvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});